### ISSUE TITLE
Error URL not working as expected

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#442]
With multi-user enabled, prior login state in my browser but a deleted Krill data directory, when browsing to the Lagosta UI and accepting the self-signed certificate I am then directed to:

https://localhost:3000/index.html#/login?withId=true&returnUrl=%2Finterstitial&error=api-logged-out

I then see the API token login form, but my Krill instance is configured to show the username/password local user login form so this is incorrect. If I then browse manually to the following URL I am shown the correct login form:

https://localhost:3000/

In the developer console in Chromium I see the following error:

```
DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at o.created (https://localhost:3000/js/app.js:137:42348)
    at nt (https://localhost:3000/js/app.js:76:11657)
    at $n (https://localhost:3000/js/app.js:76:29106)
    at o.e._init (https://localhost:3000/js/app.js:76:34469)
    at new o (https://localhost:3000/js/app.js:76:35729)
    at an (https://localhost:3000/js/app.js:76:21641)
    at init (https://localhost:3000/js/app.js:76:20507)
    at n (https://localhost:3000/js/app.js:76:21843)
    at p (https://localhost:3000/js/app.js:76:44149)
    at f (https://localhost:3000/js/app.js:76:43778)
```

**Comment by ximon18** [comment]
Fixed in PR #464.
