### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by ydahhrk** [NLnetLabs/krill#816]
Krill 0.9.4 and 0.9.5-rc8, Ubuntu 20.04. I also tested 0.9.5-rc8 in another Ubuntu 20.04, same results.

About 15-20% of the time, `krillc` panics when I pipe its output to a matching silent grep:

```
$ krillc roas list --ca ca1
192.0.2.0/24-24 => 1234

$ krillc roas list --ca ca1 | grep -q "=>"
$ krillc roas list --ca ca1 | grep -q "=>"
$ krillc roas list --ca ca1 | grep -q "=>"
$ krillc roas list --ca ca1 | grep -q "=>"

thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1201:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

("matching" means `grep`'s string exists in `krillc`'s output, and "silent" means `-q`.)

Details:

```
$ RUST_BACKTRACE=1 krillc roas list --ca ca1 | grep -q "=>"
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1201:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: std::io::stdio::print_to
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/stdio.rs:1201:9
   3: std::io::stdio::_print
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/stdio.rs:1213:5
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: tokio::park::thread::CachedParkThread::block_on
   6: krillc::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The bug is easier to trigger by piping pretty much any `krillc` output (that involves an actual server request, I think) to any `echo`:

```
$ krillc list | echo

thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1201:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Although, `krillc help | echo` also triggers a somewhat differently-phrased error in Krill 0.9.4:

```
$ krillc help | echo
thread 'main' panicked at 'Error writing Error to stdout: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/errors.rs:401:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by timbru** [comment]
Hi,

Thanks for reporting this.

This is default behaviour of the rust std library when using the `print!` macro. On my mac I don't get this issue because apparently the pipe is not closed then, but linux seems to close the pipe indeed.

I think that `krillc` should probably ignore any failure to write the output to stdout in this case. But, in case writing an error to stderr fails we should probably exit with a non-zero code, but not panic.
